- name: "Debian version check ({{ ansible_facts['distribution_major_version'] }})"
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version'] is version('10','>=')
    fail_msg: "Required version is 10+, this is {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
    quiet: true

- import_tasks: remote_logging.yml
  tags:
    - remote_logging
