- name: "Debian version check ({{ ansible_distribution_major_version }})"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('10','>=')
    msg: "Required version is 10+, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    quiet: true

- import_tasks: remote_logging.yml
  tags:
    - remote_logging
