- name: "set hostname"
  hostname:
    name: "{{ remote_logging_hostname }}"

- name: "set /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ remote_logging_hostname }}"

- name: "install ca-certificates"
  apt:
    name: ca-certificates
    state: present

- name: "install syslog-ng"
  apt:
    name: syslog-ng
    state: present

- name: "create {{ remote_logging_conf }}.conf for syslog-ng"
  when: remote_logging_enabled
  template:
    src: "{{ remote_logging_template }}"
    dest: "/etc/syslog-ng/conf.d/{{ remote_logging_conf }}.conf"
  notify: "restart syslog-ng"

- name: "remove {{ remote_logging_conf }}.conf"
  when: not remote_logging_enabled
  file:
    path: "/etc/syslog-ng/conf.d/{{ remote_logging_conf }}.conf"
    state: absent
  notify: "restart syslog-ng"

- name: Put additional remote logging configurations
  when: remote_logging_enabled and remote_logging_extra_templates
  with_items: "{{ remote_logging_extra_templates }}"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/conf.d/{{ item }}.conf"
  notify: "restart syslog-ng"

- name: "set FQDN in syslog"
  lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '^options { (.*) use_fqdn\((\w)+\);$'
    line: 'options { \1 use_fqdn(yes);'
    backrefs: yes
  notify: "restart syslog-ng"

# stats_freq(0) has changed to stats(freq(1)) in Debian 13, resulting in excess statistics in Graylog
- name: "set expected stats_freq in the syslog-ng.conf"
  ansible.builtin.replace:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: 'stats\(freq\(1\)\)'
    replace: 'stats(freq(0))'
  notify: "restart syslog-ng"

- name: "comment out writing some /var/log/ files"
  lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '^#?(.*destination\(d_{{ item }}\);.*)$'
    line: '#\1'
    backrefs: yes
  loop:
    - debug
    - messages
    - syslog
    - user
  notify: "restart syslog-ng"

- name: "flush handlers"
  meta: flush_handlers
